[package]
name = "ex01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.reqwest]
version = "0.12.8"

[dependencies.tokio]
version = "1.41.0"
features = ["full"]