services:
  ftp:
    container_name: ftp
    image: ftp:v1.0
    build: ftp
    ports:
      - 20:20
      - 21:21
    environment:
      - USR_PSW=$FTP_PSW
        #networks:
        #- inquisitor_net

  filezilla:
    container_name: fl
    image: linuxserver/filezilla
    ports:
      - 3000
      - 3001
    security_opt:
      - seccomp:unconfined

  poison:
    container_name: poison
    build: poison
      #networks:
      #- inquisitor_net

  client:
    container_name: client
    build: client
      #networks:
      #- inquisitor_net
  
  tcpdump:
    container_name: tcpdump
    build: tcpdump
