services:
  ftp:
    container_name: ftp
    image: ftp
    build: ftp
    ports:
      - 20:20
      - 21:21
    environment:
      - USR_PSW=$FTP_PSW
    networks:
      - inquisitor_net


  filezilla:
    container_name: fl
    image: linuxserver/filezilla:3.68.1-r0-ls183
    ports:
      - 3000
      - 3001
    security_opt:
      - seccomp:unconfined
    networks:
      - inquisitor_net

  poison:
    container_name: poison
    build: poison
    networks:
      - inquisitor_net

networks:
  inquisitor_net:
