services:
  mysql:
    container_name: mysql
    image: mysql:8.4.4
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
        MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - "/home/guillaume/Documents/Cybersecurity/vaccine/docker/mysql:/docker-entrypoint-initdb.d"

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
